version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: itsuppartem/foodgram_backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - backend_static:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: itsuppartem/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/media/:ro
    depends_on:
      - frontend
volumes:
  db:
  backend_static:
  media_value: